# Generated by Django 3.2 on 2021-05-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('avatar', models.ImageField(upload_to='Avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('creator', models.CharField(max_length=30)),
                ('total_members', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_User',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('userlink', models.URLField(blank=True, max_length=50)),
                ('isactive', models.BooleanField(default=False)),
                ('avatar_no', models.IntegerField(default=1, null=True)),
                ('group_id', models.ForeignKey(blank=True, db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.user_group')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='admin_page.user_role')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('doc', models.FileField(upload_to='Files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.user_group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.plan_user')),
            ],
        ),
    ]
