# Generated by Django 3.2 on 2021-05-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20210510_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='plan_user',
            name='avatar_no',
        ),
        migrations.AddField(
            model_name='plan_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Avatars/'),
        ),
        migrations.AlterField(
            model_name='doc_files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
