# Generated by Django 3.2 on 2021-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20210513_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_user',
            name='avatar',
            field=models.FileField(default='Default.jpg', upload_to='Avatars/'),
        ),
    ]
