# Generated by Django 3.1.6 on 2021-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_alter_plan_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.ImageField(upload_to='Avatar/')),
            ],
        ),
        migrations.AlterField(
            model_name='doc_files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
