# Generated by Django 3.1.6 on 2021-05-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_auto_20210513_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_user',
            name='avatar',
        ),
    ]
