# Generated by Django 3.1.6 on 2021-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0006_remove_plan_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_user',
            name='avatar',
            field=models.IntegerField(default=10),
        ),
    ]
