# Generated by Django 3.2 on 2021-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0010_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_g_id',
            field=models.IntegerField(default=0),
        ),
    ]
